[phases.setup]
nixPkgs = ["ffmpeg", "curl", "cacert"]

[phases.install]
cmds = ["mkdir -p bin && curl -L --fail --silent --show-error https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp && chmod +x bin/yt-dlp && npm install"]

[start]
cmd = "node server.js"
